### ISSUE TITLE
todoist-python is deprecated

### ISSUE THREAD

**Issue by guptadivyansh** [radeklat/todoist-habitica-sync#25]
The todoist-python package is now [deprecated](https://github.com/Doist/todoist-python), which seems to break todoist-habitica-sync. 

I tried testing just `todoist.TodoistAPI()` separately in the terminal and that returns `This API endpoint is no longer available.\n\nPlease refer to our documentation to upgrade your client to use the latest API version: https://developer.todoist.com/sync/v9/#migrating-from-v8\n\n`

The new python api (todoist-api-python) is [here](https://github.com/Doist/todoist-api-python) .

Since the API endpoints have changed, I'm not sure what would be the quickest way to make the syncer work again

**Comment by radeklat** [comment]
Hi Divyansh. Thanks for reporting this. I'll have a look tomorrow :+1:

**Comment by radeklat** [comment]
Thanks you for all the links, it made my work much faster :pray: I had a look at the new REST API (todoist-api-python) and unfortunately is doesn't expose certain task attributes that the application relies on. So I will have to stick to the Sync API for the time being.

I'm afraid the proposed solution in your PR is not going to work because the v9 API changes names of several attributes and will break when trying to deserialise.

Given the fact that this sync app uses only a single endpoint of the API, I will drop reliance on any libraries and call the endpoint directly instead. I should have a fix by the end of this week. Apologies for the inconvenience. If it is any consolation, I'm affected by this as well so it is in my best interest to fix this ASAP.
