### ISSUE TITLE
Priority is out of order

### ISSUE THREAD

**Issue by RandomUser123467** [radeklat/todoist-habitica-sync#52]
The Priority right now is: 
p1 | Medium | Important, urgent
p2 | Hard | Important, not urgent
p3 | Easy | Not important, urgent
p4 | Trivial | Not important, not urgent

Shouldn't it be:
p1 | Hard | Important, urgent
p2 | Medium | Important, not urgent
p3 | Easy | Not important, urgent
p4 | Trivial | Not important, not urgent

**Comment by RandomUser123467** [comment]
Also if this script isn't running and I complete a few Todoist tasks does it still add them to Habitica when I run it again?

**Comment by radeklat** [comment]
Hey @RandomUser123467. The reasoning for this swap was explained in the README. However, I understand that it's not expected behaviour and may not fit everyone's use case. So I added a configuration option in [3.3.0](https://github.com/radeklat/todoist-habitica-sync/blob/main/CHANGELOG.md#330---2024-12-15) that allows set the mapping from Todoist priorities to Habitica difficulties. It also now default to your suggested mapping.

As for the second question - yes it will. The script remembers the last seen state. So as long as the tasks existed, it will score points on the next run when they appear as completed.
